### ISSUE TITLE
Đề xuất: thêm thư viện testlib

### ISSUE THREAD

**Issue by thanhchauns2** [mely-apps/mely-oj#11]
![image](https://user-images.githubusercontent.com/69909023/229284967-06209464-1341-4826-ba12-f23b400f0dc1.png)

Nếu tạo như này thì sẽ được 2 bộ test khác nhau trên 2 môi trường khác nhau, còn nếu dùng testlib thì sẽ được cùng 1 bộ test.

**Comment by nyagami** [comment]
Đã thêm ✅
#13 
https://github.com/mely-apps/judge-server/pull/1
