### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by thanhchauns2** [mely-apps/mely-oj#4]
![image](https://user-images.githubusercontent.com/69909023/229279733-867fdaee-0556-4e7e-aa73-84da49b761d6.png)

Lúc đăng kí để default language là Python3, nhưng lúc submission vẫn hiện Assembly lên đầu tiên.

(Có vẻ không quan trọng lắm)

**Comment by nyagami** [comment]
Hình như anh chọn mặc định là c++17, mà bài tập này thì chưa gán ngôn ngữ c++17, nên nó chọn lại thánh Assem

**Comment by nyagami** [comment]
E vừa thêm rồi, a check thử đi

**Comment by thanhchauns2** [comment]
Oke, hiện C++17 rồi
