### ISSUE TITLE
Admin section

### ISSUE THREAD

**Issue by thanhchauns2** [mely-apps/mely-oj#5]
![image](https://user-images.githubusercontent.com/69909023/229279974-f3de5732-c835-4ecc-9e23-58eb6339e67c.png)

Nên ẩn thanh admin này đi, chỉ để những người có thẩm quyền thấy

**Comment by nyagami** [comment]
Do em phân cho a quyền admin rồi.

**Comment by thanhchauns2** [comment]
à oke
