### ISSUE TITLE
Group/Organization

### ISSUE THREAD

**Issue by thanhchauns2** [mely-apps/mely-oj#6]
![image](https://user-images.githubusercontent.com/69909023/229280122-c3cc49a2-54a0-4e17-a2a3-2fb7e073441d.png)

Nên thêm section group/organization ở đây, mỗi người có thể tham gia nhiều organization.

Giao diện có thể tham khảo như sau (ảnh từ VNOJ)

![image](https://user-images.githubusercontent.com/69909023/229280179-6587a90f-6e2f-4d83-98d5-1d4343283878.png)

Mỗi org cần các trường: info, users. Có thể thêm sau này: problems, submissions, contests, chế độ hiển thị public/private

Để tham gia 1 org, có 2 option: tham gia tự do/cần phê duyệt

**Comment by nyagami** [comment]
![image](https://user-images.githubusercontent.com/86464880/229284521-bc2e4dc9-b1df-423b-92ee-055b43a71a4b.png)
e chưa hiểu lắm, nó có rồi mà
