### ISSUE TITLE
Notification after registering

### ISSUE THREAD

**Issue by thanhchauns2** [mely-apps/mely-oj#7]
Đăng kí xong không được thông báo kiểm tra gmail để xác nhận, nhưng đúng là phải cần xác nhận mới dùng được tài khoản

**Comment by nyagami** [comment]
![image](https://user-images.githubusercontent.com/86464880/235340616-d0a4696f-e6b9-47d6-8891-d80d1b89cf20.png)
Có mà nhỉ.
